import type { Flow, FlowResult } from "@tz/agent-core";
import { formatTzs, ISIC_ACTIVITIES } from "@tz/shared";
import { renderPdf } from "../pdf.js";

/**
 * Generate the incorporation document set from the company profile:
 * Memorandum & Articles of Association, Declaration of Compliance, and the
 * first board resolution. With an ANTHROPIC_API_KEY the objects clauses are
 * drafted by Claude (added in the AI phase); here we build them deterministically
 * from the profile so the pipeline works offline.
 */
export const generateMemarts: Flow = async (ctx): Promise<FlowResult> => {
  const company = await ctx.repo.getCompany(ctx.companyId);
  const people = await ctx.repo.getPeople(ctx.companyId);
  const directors = people.filter((p) => p.roles.includes("director"));
  const shareholders = people.filter((p) => p.roles.includes("shareholder"));

  const activityLabels = company.businessActivityIsic.map((code) => {
    const found = ISIC_ACTIVITIES.find((a) => a.code === code);
    return found ? `${found.label} (ISIC ${code})` : `ISIC ${code}`;
  });

  const objectsClauses = [
    `To carry on the business of ${company.activityDescription}.`,
    ...activityLabels.map((l) => `To engage in ${l}.`),
    "To do all such other things as are incidental or conducive to the attainment of the above objects.",
  ];

  const shareTable = shareholders
    .map((s) => `  • ${s.fullName} — ${s.sharesHeld} shares`)
    .join("\n");

  const memarts = await renderPdf({
    title: "Memorandum & Articles of Association",
    subtitle: `${company.name} — a private company limited by shares`,
    sections: [
      {
        heading: "1. Name",
        body: `The name of the Company is "${company.name}".`,
      },
      {
        heading: "2. Registered Office",
        body: `The registered office of the Company will be situated at ${company.physicalAddress}, ${company.district}, ${company.region}, in the United Republic of Tanzania.`,
      },
      {
        heading: "3. Objects",
        body: objectsClauses.map((c, i) => `(${i + 1}) ${c}`).join("\n"),
      },
      {
        heading: "4. Liability",
        body: "The liability of the members is limited by shares.",
      },
      {
        heading: "5. Share Capital",
        body: `The share capital of the Company is ${formatTzs(company.shareCapitalTzs)} divided into ${company.totalShares} ordinary shares.\n\nSubscribers:\n${shareTable}`,
      },
      {
        heading: "6. Directors",
        body: directors.map((d) => `  • ${d.fullName} (TIN ${d.tin ?? "—"})`).join("\n"),
      },
    ],
    footer: "Generated by tz-compliance for filing on BRELA ORS.",
  });

  const declaration = await renderPdf({
    title: "Declaration of Compliance",
    subtitle: `Companies Act (Cap. 212) — ${company.name}`,
    sections: [
      {
        heading: "Declaration",
        body: `I, ${directors[0]?.fullName ?? "the applicant"}, declare that all the requirements of the Companies Act (Cap. 212) in respect of the registration of ${company.name} and of matters precedent and incidental thereto have been complied with.`,
      },
    ],
    footer: "Executed for the purposes of company incorporation.",
  });

  const boardResolution = await renderPdf({
    title: "First Board Resolution",
    subtitle: company.name,
    sections: [
      {
        heading: "Resolved",
        body: [
          "1. THAT the Certificate of Incorporation be accepted.",
          "2. THAT a corporate bank account be opened and the following persons be authorized signatories:",
          people
            .filter((p) => p.roles.includes("signatory") || p.roles.includes("director"))
            .map((p) => `     • ${p.fullName}`)
            .join("\n"),
          "3. THAT the registered office be as stated in the Memorandum.",
        ].join("\n"),
      },
    ],
  });

  const memartsDoc = await ctx.repo.addDocument({
    companyId: ctx.companyId,
    stepRunId: ctx.stepRunId,
    kind: "memarts",
    title: `Memorandum & Articles — ${company.name}`,
    data: memarts,
    source: "generated",
  });
  const declDoc = await ctx.repo.addDocument({
    companyId: ctx.companyId,
    stepRunId: ctx.stepRunId,
    kind: "declaration_of_compliance",
    title: `Declaration of Compliance — ${company.name}`,
    data: declaration,
    source: "generated",
  });
  const resolutionDoc = await ctx.repo.addDocument({
    companyId: ctx.companyId,
    stepRunId: ctx.stepRunId,
    kind: "board_resolution",
    title: `First Board Resolution — ${company.name}`,
    data: boardResolution,
    source: "generated",
  });

  await ctx.actions.record({
    kind: "extract",
    detail: `Generated Memarts, Declaration of Compliance, and board resolution (${objectsClauses.length} objects clauses)`,
  });

  return {
    output: {
      memartsDocumentId: memartsDoc.id,
      declarationDocumentId: declDoc.id,
      boardResolutionDocumentId: resolutionDoc.id,
    },
  };
};
