import PDFDocument from "pdfkit";

export interface CertificateOpts {
  authority: string; // e.g. "BRELA — Business Registrations and Licensing Agency"
  title: string; // e.g. "Certificate of Incorporation"
  entityName: string;
  number: string;
  date: string;
  extraLines?: string[];
}

/** Generate a simple one-page certificate PDF and resolve with its bytes. */
export function certificatePdf(opts: CertificateOpts): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 50 });
    const chunks: Buffer[] = [];
    doc.on("data", (c: Buffer) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const w = doc.page.width;

    // Border box
    doc.lineWidth(2).rect(30, 30, w - 60, doc.page.height - 60).stroke("#1a3e6e");
    doc.lineWidth(0.5).rect(38, 38, w - 76, doc.page.height - 76).stroke("#1a3e6e");

    doc.fillColor("#1a3e6e").font("Helvetica-Bold").fontSize(14);
    doc.text("THE UNITED REPUBLIC OF TANZANIA", 50, 70, { align: "center", width: w - 100 });
    doc.fontSize(12).text(opts.authority, { align: "center", width: w - 100 });
    doc.moveDown(2);

    doc.fontSize(20).fillColor("#000").text(opts.title.toUpperCase(), { align: "center", width: w - 100 });
    doc.moveDown(1.5);

    doc.font("Helvetica").fontSize(12);
    doc.text("This is to certify that", { align: "center", width: w - 100 });
    doc.moveDown(0.5);
    doc.font("Helvetica-Bold").fontSize(16).text(opts.entityName, { align: "center", width: w - 100 });
    doc.moveDown(1);

    doc.font("Helvetica").fontSize(12);
    doc.text(`Number: ${opts.number}`, { align: "center", width: w - 100 });
    doc.text(`Date: ${opts.date}`, { align: "center", width: w - 100 });
    for (const line of opts.extraLines ?? []) {
      doc.text(line, { align: "center", width: w - 100 });
    }

    // QR-ish box with the number
    const qx = w / 2 - 40;
    const qy = doc.y + 30;
    doc.lineWidth(1).rect(qx, qy, 80, 80).stroke("#000");
    doc.fontSize(7).text(opts.number, qx, qy + 36, { align: "center", width: 80 });

    doc.fontSize(9).fillColor("#555");
    doc.text("Generated by the tz-compliance portal simulator (not a real document).", 50, doc.page.height - 90, {
      align: "center",
      width: w - 100,
    });

    doc.end();
  });
}
